apiVersion: v1
kind: Secret
metadata:
  name: otusapp-secret
type: Opaque
data:
  DB_URI: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase| b64enc | quote }}
  DB_USER: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASSWD: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}