apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otusapp-chart.fullname" . }}
  labels:
    {{- include "otusapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otusapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otusapp-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          envFrom:
            - secretRef:
                name: otusapp-secret
          ports: 
            - containerPort: 8000