apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: otusapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/vitalyusov($|/)(.*)
          backend:
            serviceName: {{ include "otusapp-chart.fullname" . }}
            servicePort: {{ .Values.service.port }}
